#k=v
#对空格的要求十分高
#普通的key-value
#name: 迪丽热巴
#
## 对象
#student:
#  name: 迪丽热巴
#  age: 28
#
##行内写法
#studnet: {name: 迪丽热巴,age: 28}
#
##数组
#pets:
#  - cat
#  - dog
#  - pig
#
#pet: [cat,dog,pig]
#person:
#  name: 迪丽热巴
#  age: ${random.int}
#  happy: false
#  birth: 2021/12/05
#  maps: {k1: v1,k2: v2}
#  lists:
#    - code
#    - music
#    - boy
#  dog:
#    name: ${person.hello:hello}_旺财
#    age: 3
#
#dog:
#  first-name: 啊黄
#  age: 3

#  空检查
#  @Null       验证对象是否为null
#  @NotNull    验证对象是否不为null, 无法查检长度为0的字符串
#  @NotBlank   检查约束字符串是不是Null还有被Trim的长度是否大于0,只对字符串,且会去掉前后空格.
#  @NotEmpty   检查约束元素是否为NULL或者是EMPTY.
#
#  Booelan检查
#  @AssertTrue     验证 Boolean 对象是否为 true
#  @AssertFalse    验证 Boolean 对象是否为 false
#
#  长度检查
#  @Size(min=, max=) 验证对象（Array,Collection,Map,String）长度是否在给定的范围之内
#  @Length(min=, max=) string is between min and max included.
#
#  日期检查
#  @Past       验证 Date 和 Calendar 对象是否在当前时间之前
#  @Future     验证 Date 和 Calendar 对象是否在当前时间之后
#  @Pattern    验证 String 对象是否符合正则表达式的规则
#
#  .......等等
#  除此以外，我们还可以自定义一些数据校验规则